"""Add Client model update

Revision ID: 25f259159c4b
Revises: 462c100a1c72
Create Date: 2024-11-25 02:52:42.235577

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '25f259159c4b'
down_revision: Union[str, None] = '462c100a1c72'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clients',
    sa.Column('client_name', sa.String(length=255), nullable=False),
    sa.Column('date_added', sa.Date(), nullable=False),
    sa.Column('number_of_properties', sa.Integer(), nullable=False),
    sa.Column('average_property_value', sa.Float(), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=False),
    sa.Column('added_by_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('time_created', sa.DateTime(), nullable=True),
    sa.Column('time_updated', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['added_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
  
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
  
    op.drop_table('clients')
    # ### end Alembic commands ###
