"""adding user last login col

Revision ID: ab2839a49b82
Revises: b685a83df574
Create Date: 2024-11-24 16:41:22.670765

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab2839a49b82'
down_revision: Union[str, None] = 'b685a83df574'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
 
    op.add_column('users', sa.Column('last_login', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_login')
    # ### end Alembic commands ###
