"""adding user and property table

Revision ID: dc770112cd74
Revises: 
Create Date: 2024-10-28 03:37:18.377070

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dc770112cd74'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('properties',
    sa.Column('property_id', sa.String(), nullable=True),
    sa.Column('property_url', sa.String(), nullable=True),
    sa.Column('sku', sa.String(), nullable=True),
    sa.Column('property_descr', sa.String(), nullable=True),
    sa.Column('feature_image', sa.String(), nullable=True),
    sa.Column('unit', sa.String(), nullable=True),
    sa.Column('street_address', sa.String(), nullable=True),
    sa.Column('area', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('postal_code', sa.String(), nullable=True),
    sa.Column('region_code', sa.String(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('property_status', sa.String(), nullable=True),
    sa.Column('house_price', sa.String(), nullable=True),
    sa.Column('rental_estimate', sa.String(), nullable=True),
    sa.Column('estimated_value', sa.String(), nullable=True),
    sa.Column('rental_yield', sa.String(), nullable=True),
    sa.Column('rental_dom', sa.String(), nullable=True),
    sa.Column('tax', sa.String(), nullable=True),
    sa.Column('tax_year', sa.String(), nullable=True),
    sa.Column('year_build', sa.String(), nullable=True),
    sa.Column('size', sa.String(), nullable=True),
    sa.Column('size_unit', sa.String(), nullable=True),
    sa.Column('lot_size', sa.String(), nullable=True),
    sa.Column('lot_size_unit', sa.String(), nullable=True),
    sa.Column('maintenance_fees', sa.String(), nullable=True),
    sa.Column('parking', sa.String(), nullable=True),
    sa.Column('bedrooms', sa.String(), nullable=True),
    sa.Column('bathrooms', sa.String(), nullable=True),
    sa.Column('garage', sa.String(), nullable=True),
    sa.Column('type_home', sa.String(), nullable=True),
    sa.Column('listing_date', sa.Date(), nullable=True),
    sa.Column('updated_on', sa.Date(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('time_created', sa.DateTime(), nullable=True),
    sa.Column('time_updated', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('property_id', 'id')
    )
    op.create_table('users',
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('password', sa.LargeBinary(), nullable=False),
    sa.Column('password_salt', sa.LargeBinary(), nullable=False),
    sa.Column('is_super_admin', sa.Boolean(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('time_created', sa.DateTime(), nullable=True),
    sa.Column('time_updated', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('properties')
    # ### end Alembic commands ###
