"""adding user last login col

Revision ID: e8def3d10664
Revises: c9d25e356bfb
Create Date: 2024-11-24 17:10:50.730131

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e8def3d10664'
down_revision: Union[str, None] = 'c9d25e356bfb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("users", "last_login",  type = sa.DateTime(),existing_type=sa.Date)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
