"""adding new cols in properties table

Revision ID: fea681fdd588
Revises: e8def3d10664
Create Date: 2024-11-24 19:22:11.412042

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fea681fdd588'
down_revision: Union[str, None] = 'e8def3d10664'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('properties', sa.Column('is_active', sa.Boolean(), server_default=sa.text("true"),nullable=True))
    op.add_column(
        "properties",
        sa.Column(
            "is_sufficient_data",
            sa.Boolean(),
            server_default=sa.text("true"),
            nullable=True,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('properties', 'is_sufficient_data')
    op.drop_column('properties', 'is_active')
    # ### end Alembic commands ###
